[[proxy]]
rewrite = "/api"
backend = "https://api.tsodev.fr/api"

[build]
target = "index.html"
dist = "dist"
watch = ["src/**/*.rs", "index.html", "style/input.css"]

# Hook pour exécuter Tailwind CSS
[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
  "-c",
  "npx @tailwindcss/cli -i style/input.css -o style/output.css",
]
